server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: messages
  security:
    user:
      name: 1234
      password: 12345
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb

management:
  endpoints:
    web:
      exposure:
        include: "*"

